### ISSUE TITLE
Return string when not a union

### ISSUE THREAD

**Issue by G-Rath** [kimamula/ts-transformer-enumerate#12]
This feature might be impossible to type (and/or might fit as another transformer):

When I have a type that's of only one string, it'd be awesome to have that string returned, rather than an `object` with that string as a property:

```
type ENDPOINT = '/api/users/:userId';

const t = enumerate<API.Users.ShowSingleUser.ENDPOINT>();

console.log(t);
```

Currently the above will have the value `{ '/api/users/:userId': '/api/users/:userId' }`, where I'd prefer it to have the value `'/api/users/:userId'`.

While I know this is possible in the transformer, it might be impossible to type, as I don't know if there is a way of saying "if is a union" in the generic typing system.

This might alternatively fit as a new transformer, something like `ts-transformer-inline`, where it takes the first element (making it compatible with unions) - but again, this might be impossible to properly type (this could also just be stated in the readme as a note, similar to generic types) :/

Regardless, I'll use this issue to thank you for two very awesome transformers! I love them - I've been trying to find more cool transformers, but you seem to be the only one making them :(

**Comment by G-Rath** [comment]
Because that won't work with `declare`, and it means I have to define the property twice, in a coupled manner.

I mean, you could say that about this transformers function - why not just use a `const enum`?

**Comment by kimamula** [comment]
I see.

Well, I don't think it is good to introduce this feature into `ts-transformer-enumerate`, not only because it would be impossible to type as you mentioned, but also because the behavior would be unexpected for most of the users.

If you create a new transformer, I think you can type your function as follows.

```ts
declare function inline<T extends string>(): T;
```
