### ISSUE TITLE
`isEnumerateCallExpression` sometimes returns `false` when it should return `true`

### ISSUE THREAD

**Issue by davidmurdoch** [kimamula/ts-transformer-enumerate#25]
I have a complex monorepo using _uncompiled_ typescript via ts-node and ttypescript.

I've found that within the function `isEnumerateCallExpression` `declaration.getSourceFile().fileName === indexTs` may evaluate to `false` when it should be `true`.

A potential fix for this is to copy the `isOurStubModule` function from `ts-transformer-inline-file` and use it, instead, like this:

```javascript
const stubModuleSource = fs.readFileSync(path.join(__dirname, 'index.d.ts'), 'utf8');
function isOurStubModule(sourceFile) {
    // Comparing of the file names may not be reliable, it doesn't work e.g. with
    // yarn's "link" resolution used in this module's end-to-end tests.
    return sourceFile.text === stubModuleSource;
}
function isEnumerateCallExpression(node, typeChecker) {
    if (!ts.isCallExpression(node)) {
        return false;
    }
    var signature = typeChecker.getResolvedSignature(node);
    if (typeof signature === 'undefined') {
        return false;
    }
    var declaration = signature.declaration;
    return !!declaration
        && isOurStubModule(declaration.getSourceFile()) // <----- HERE -----
        && !!declaration.name
        && declaration.name.getText() === 'enumerate';
}
```

(sorry about the JavaScript snippet, I was hacking on directly within my node_modules)

**Comment by kimamula** [comment]
There was [a similar problem](https://github.com/kimamula/ts-transformer-keys/issues/47) in `ts-transformer-keys`, which has been already resolved.
I fixed `ts-transformer-enumerate` in the same way and released `v0.5.2`. Please give it a try and see if the issue is fixed.
